# Site settings
title: Common Lisp
domain: "lisp-lang.org"

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: none

defaults:
  - scope:
      path: "learn"
    values:
      layout: "learn"
      permalink: "/learn/:title"
      css_file: "learn"
  - scope:
      path: "success"
    values:
      layout: "success"
      css_file: success
  - scope:
      path: "learn/_posts/tutorials"
    values:
      kind: "tutorial"
  - scope:
      path: "learn/_posts/guides"
    values:
      kind: "guide"
