# Site settings
title: Common Lisp
domain: "lisp-lang.org"

# Build settings
markdown: kramdown
sass:
    style: :compressed

defaults:
  - scope:
      path: "learn"
    values:
      layout: "learn"
      permalink: "/learn/:title"
  - scope:
      path: "success"
    values:
      layout: "success"
