# Site settings
title: Common Lisp
domain: "lisp-lang.org"

# Build settings
markdown: kramdown
sass:
    style: :compressed

defaults:
  - scope:
      path: ""
    values:
      css_file: "page"
  - scope:
      path: "learn"
    values:
      layout: "learn"
      permalink: "/learn/:title"
      css_file: "learn"
  - scope:
      path: "success"
    values:
      layout: "success"
  - scope:
      path: "learn/_posts/tutorials"
    values:
      kind: "tutorial"
  - scope:
      path: "learn/_posts/guides"
    values:
      kind: "guide"
