# Site settings
title: Common Lisp
description: Site description
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

# Variables
impls:
  - name: SBCL
    fullname: Steel Bank Common Lisp
    tagline: Peak performance, always
  - name: CCL
    fullname: Clozure Common Lisp
    tagline: Run anywhere
  - name: ABCL
    fullname: Armed Bear Common Lisp
    tagline: Tight JVM integration
  - name: mocl
    tagline: Run on iOS, Android and OS X
